#!/bin/bash

##################################################
# submit working draft to IETF via API
# from https://datatracker.ietf.org/api/submit/
# 2020-08 : @mamund
##################################################

# local args
url="https://datatracker.ietf.org/api/submit "

# check for folder/doc
# arg is draft-02 where
# the subfolder/file is draft-02/draft-02.xml
if [ -z "$1" ]
  then
    echo "No document supplied"
    echo "$0 <folder> <user>"
    exit
fi

# check for username
# MUST be a valid IETF datatracker account
if [ -z "$2" ]
  then
    echo "No user supplied"
    echo "$0 <folder> <user>"
    exit
fi

# do the work
echo "user=$2"
echo "xml=$1/$1.xml"
echo "posting to $url..."
curl -S -F "user=$2" -F "xml=@$1/$1.xml" $url 
echo "job completed."

#
# EOF
#
